# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x07greeter\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"5\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x17\n\x07KeyList\x12\x0c\n\x04keys\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xcc\x01\n\rKeyValueStore\x12\x34\n\x03Put\x12\x11.greeter.KeyValue\x1a\x1a.greeter.OperationResponse\x12#\n\x03Get\x12\x0c.greeter.Key\x1a\x0e.greeter.Value\x12\x32\n\x06\x44\x65lete\x12\x0c.greeter.Key\x1a\x1a.greeter.OperationResponse\x12,\n\x08ListKeys\x12\x0e.greeter.Empty\x1a\x10.greeter.KeyListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=26
  _globals['_KEYVALUE']._serialized_end=64
  _globals['_KEY']._serialized_start=66
  _globals['_KEY']._serialized_end=84
  _globals['_VALUE']._serialized_start=86
  _globals['_VALUE']._serialized_end=108
  _globals['_OPERATIONRESPONSE']._serialized_start=110
  _globals['_OPERATIONRESPONSE']._serialized_end=163
  _globals['_KEYLIST']._serialized_start=165
  _globals['_KEYLIST']._serialized_end=188
  _globals['_EMPTY']._serialized_start=190
  _globals['_EMPTY']._serialized_end=197
  _globals['_KEYVALUESTORE']._serialized_start=200
  _globals['_KEYVALUESTORE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
